apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app
  namespace: production
  labels:
    app: capstone
    environment: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone
      environment: production
  template:
    metadata:
      labels:
        app: capstone
        environment: production
    spec:
      containers:
      - name: app
        image: capstonetfacr047af007.azurecr.io/ecommerce-app:v23
        ports:
        - containerPort: 8000

        envFrom:
        - secretRef:
            name: app-secrets

        env:
        - name: AZURE_REGION
          value: "southeastasia"
        - name: APP_ENVIRONMENT
          value: "production"

        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"

        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
